### ISSUE TITLE
Crash in cupcake.world

### ISSUE THREAD

**Issue by mindfuq** [Yonom/CupCake#68]
Bot crashes for reason somewhere in this file. Really annoying.
I cant say anything else except the only varying values are "GravityNothing"(sometimes GravityLeft)and "layer 117"(any number else)
Crashlog:
 --- Connection established ---
^^^ Started server on 127.0.0.1:50315
*** Welcome to CupCake! (API version: 1.9.2)
*** Loading plugin dlls...
*** Joining room...
*** Starting plugins...
*** Done.
[17:15:48] (Error) <CupCake.World> Exception when parsing block GravityNothing on layer 117. The error was: Value at index:45 is not System.Byte[]. It's a System.Int32. Value is: 0
System.InvalidCastException: Value at index:46 is not System.Int32. It's a System.Byte[]
   в PlayerIOClient.Internal.identifier957.getNumeric[T](UInt32 index, Byte expectedType)
   в CupCake.World.WorldService.ParseWorld(Message m, Int32 sizeX, Int32 sizeY, UInt32 offset)
   в CupCake.World.WorldService.OnInit(Object sender, InitReceiveEvent e)
   в CupCake.Core.Events.EventHandle`1.Raise(Object sender, T e)
   в CupCake.Messages.MessageService.HandleMessage(Message e)
   в Nito.Async.ActionDispatcher.Run()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()
--- Connection terminated ---

**Comment by Yonom** [comment]
Should be fixed now.
